Implement `Bits` and `BMap`
HigherOrderCO/kind pull request #9
Opened 2024-04-01 21:05 UTC by edusporto

2024-04-03 14:41 UTC, developedby requested changes

2024-04-03 14:41 UTC, developedby commented on book/BMap/has.kind2
All these functions to get a property should by default not consume the map, but instead return a pair like the `got` and be linear (not duplicate anything unnecessary).
Having the option of a function that consumes the map but has a simpler return is ok, but realistically it won't be used as often

2024-04-03 14:41 UTC, developedby commented on book/BMap/size.kind2
Same here

2024-04-03 14:41 UTC, developedby commented on book/BMap/set.kind2
> +      // NOTE: New intermediary notes have their value set to `none`
Don't need this note twice

2024-04-04 16:48 UTC, edusporto commented
@developedby suggested changes resolved

2024-07-20 19:38 UTC, closed without merging